### ISSUE TITLE
Propuestas

### ISSUE THREAD

**Issue by gonzaloLaqui147** [gonzaloLaqui147/FILEEXP-Trabajo_Final#8]
Para el correcto desarrollo de este proyecto se hara uso de la Programación Orientada a Objetos (POO), con el fin de permitir la interacción de datos que ingresan al sistema y la respuesta que se muestra al usuario en base a ella, y datos abstractos como arboles, con el fin de relacionar ciertos archivos entre ellos.

**Comment by rcucho** [comment]
[Modelo1-TF-Algo.zip](https://github.com/gonzaloLaqui147/FILEEXP-Trabajo_Final/files/3784663/Modelo1-TF-Algo.zip)
modelo para avanzar
